name: Convertir Excel a YAML Automáticamente

on:
  push:
    paths:
      - '_data/*.csv' # Solo se ejecuta si cambias un CSV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Instalar Dependencias
      run: pip install pyyaml # ESTO ES VITAL
        
    - name: Ejecutar Conversion
      run: python convertir_datos.py
      
    - name: Subir Cambios
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/*.yml
        git commit -m "Auto-update YAML desde CSV" || exit 0
        git push